config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#index'
  get 'about', to: 'pages#about'
  resources :articles # , only: %i[show index new create edit update destroy]
  # %i = Non-interpolated Array of symbols, separated by whitespace
  get 'signup', to: 'users#new'
  resources :users, except: %i[new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name

  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true, uniqueness: { case_sensitivity: false }, length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d-]+(\.[a-z\d-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitivity: false },
                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Whatever we add to application controller will be available to all other Controlers
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    # The !! turns the following variable into a boolean
    !!current_user
  end

  def require_user
    return if logged_in?

    flash[:alert] = 'You must be logged in'
    redirect_to login_path
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  before_action :require_user, except: %i[show index]
  before_action :require_same_user, only: %i[edit update destroy]

  def show
    puts 'THIS IS HAPPENING'
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit; end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      # redirect_to article_path(@article)
      flash[:notice] = 'Article was created successfully' # There are two types a flashs typically :notice, and "alert"
      redirect_to @article
    else
      puts @article.errors.full_messages
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = 'Article was updated successfully'
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    puts('NOW THIS IS HAPPENING', @article)
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    return unless current_user != @article.user && !current_user.admin

    flash[:alert] = 'You can only edit or delete your own article'
    redirect_to @article
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: %i[index show]

  def new
    @category = Category.new
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category was successfully created'
      redirect_to @category
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = 'Category was successfully updated'
      redirect_to @category
    else
      render 'edit'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    return if logged_in? && current_user.admin?

    flash[:alert] = 'Only admin can perform that action'
    redirect_to categories_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    redirect_to articles_path if logged_in?
  end

  def about; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = 'Logged In'
      redirect_to user
    else
      # Because we are not redirecting we need to use flash.now
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Logged Out'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :require_user, only: %i[edit update destroy]
  before_action :require_same_user, only: %i[edit update destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to my blog #{@user.username}"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:notice] = 'Your account information was successfully updated!'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = 'Your account was successfully deleted!'
    redirect_to root_path
  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    return unless current_user != @user && !current_user.admin

    flash[:alert] = 'You can only edit or delete your own account'
    redirect_to @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    # The !! turns the following variable into a boolean
    !!current_user
  end

  def flash_class(level)
    case level.to_sym
    when :notice then 'alert alert-success'
    when :success then 'alert alert-success'
    when :error then 'alert alert-error'
    when :alert then 'alert alert-error'
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_articles.html.erb
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Author</th>
      <th>Categories</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to article.user.username, user_path(article.user) %></td>
        <td>
          <% if article.categories.any? %>
              <%= render article.categories %>
          <% end %>
        </td>
        <td>
          <%= link_to 'Show', article, class: "btn btn-primary" %>
          <% if logged_in? && (article.user == current_user || current_user.admin?) %>
            <%= link_to 'Edit', edit_article_path(article), class: "btn btn-warning" %>
            <%= link_to 'Delete', article, data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<%=  form_with(model: @article, local: true, data: { turbo: false }) do |f|%>
  <div class="form-group">
    <%= f.label :title %> <br/>
    <%= f.text_field :title, class: "form-control", placeholder: "Enter Title" %> <br/>
  </div>
  <div class="form-group">
    <%= f.label :description %> <br/>
    <%= f.text_area :description, class: "form-control", placeholder: "Enter Description" %> <br/>
  </div>
  <div class="form-group">
    <%= f.label :category %> <br/>
    <%= f.collection_select(:category_ids, Category.all, :id, :name, {prompt: "Select a Category"}, {multiple: true, class: "form-select"}) %>
  </div>
  <%= f.submit class: "btn btn-primary mr-2" %>
  <%= link_to '[ Cancel and return to Articles ]', articles_path %>
<% end %>

app/views/articles/edit.html.erb
<div class="container mt-4">
  <h1>Update Article</h1>
  <%= render 'form' %>
</div>

app/views/articles/index.html.erb
<div class="container margin-top">
  <h1>Articles listing page <% if logged_in? %>
      <%= link_to new_article_path, class: "btn btn-primary" do %>
        <i class="bi bi-plus-circle"></i> New Article
      <% end %>
    <% end %>
  </h1>
  <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>
  <%= render 'articles' %>
  <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container">
  <h1>Create a new Article</h1>
  <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<div class="container margin-top">
  <div class="row">
    <div class="col-md-12">
      <h1 class="my-4"><%= @article.title %></h1>
      <% if @article.categories.any? %>
        <div class="row row-cols-6 mb-4">
          <%= render @article.categories %>
        </div>
      <% end %>
      <p><%= @article.description %></p>
      <hr>
      <div class="row p-2">
        <div class="d-flex justify-content-end">By <strong class="d-block ms-1"><%= @article.user.username %></strong></div>
      </div>
      <% if logged_in? && @article.user == current_user || current_user.admin? %>
        <div class="d-flex justify-content-end">
          <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-primary mx-2" %>
          <%= link_to 'Delete', @article, data: {  turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger mx-2" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category, class: "p-2 me-2 badge rounded-pill bg-dark fit-content d-inline-block" %>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
<%= form_with(model: @category, local: true, data: { turbo: false }) do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control", placeholder: "Enter a Name" %>
  </div>
  <%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/categories/edit.html.erb
<div class="container">
  <h1>Edit Category Name</h1>
  <%= render 'form' %>
</div>

app/views/categories/index.html.erb
<div class="container">
  <div class="row">
    <h1>
      Categories <% if logged_in? && (current_user.admin?) %>
        <%= link_to 'Create Category', new_category_path, class: "btn btn-primary" %>
      <% end %>
    </h1>
  </div>
  <div class="row">
    <div class="flickr_pagination">
      <%= will_paginate @categories, :container => false %>
    </div>
  </div>
  <div class="row">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Name</th>
          <th># of Articles</th>
          <% if logged_in? && (current_user.admin?) %>
            <th>Actions</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td><%= link_to category.name, category, class: "btn btn-primary" %></td>
            <td><%= pluralize(category.articles.count, "category") %></td>
            <% if logged_in? && (current_user.admin?) %>
              <td>
                <%= link_to 'Delete', category, data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger" %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="row">
    <div class="flickr_pagination">
      <%= will_paginate @categories, :container => false %>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<div class="container mt-4">
  <div class="row">
    <h1>Create Category</h1>
  </div>
  <div class="row">
    <%= render 'form' %>
  </div>
  <%= link_to '[ Cancel and return to Articles ]', articles_path %>
</div>

app/views/categories/show.html.erb
<div class="container mt-4">
  <div class="row">
    <h1>
      <%= @category.name %>
        <% if logged_in? && current_user.admin %>
      <%= link_to 'Edit', edit_category_path(@category), class: "btn btn-warning" %>
    <% end %>
    </h1>

  </div>
  <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>
  <%= render 'articles/articles' %>
  <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>
</div>

app/views/layouts/_messages.html.erb
 <% flash.each do |name, msg| %>
  <%= msg %>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <h3 class="ms-3">
      <% if logged_in? %>
        <%= link_to current_user.username, user_path(current_user) %>
      <% else %>
        Blog
      <% end %>
    </h3>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Home', root_path %>
      </li>
      <li class="nav-item">
        <%= link_to 'Articles', articles_path %>
      </li>
      <li class="nav-item">
        <%= link_to 'Categories', categories_path %>
      </li>
      <li class="nav-item">
        <%= link_to 'About', about_path %>
      </li>
      <li class="nav-item">
        <%= link_to 'Users', users_path %>
      </li>
      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to 'Logout', logout_path, data: { turbo_method: :delete} %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log In', login_path %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Up', signup_path %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_include_tag "turbo", type: "module" %>
    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'layouts/nav' %>
    <% flash.each do |type, msg| %>
      <div class="container">
        <div class="<%= flash_class(type) %> alert-dismissible fade show" role="alert">
          <%= msg %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      </div>
    <% end %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

app/views/pages/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 center">
      <h1>Welcome to my Blog</h1>
      <p class="mb-4">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque metus eget quam mollis ullamcorper. Sed ultricies nisi a odio dictum, quis dapibus tellus pharetra. Ut sit amet ex velit. Donec id nulla vel erat consequat volutpat a eu purus. Pellentesque in enim in diam auctor suscipit. Nullam id mollis ipsum.</p>
      <%= link_to 'Sign Up!', signup_path, class: "btn btn-primary btn-lg" %>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any?  %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved.</h4>
    <ul>
      <% obj.errors.full_messages.each do |message|  %>
        <li><%= message %></li>
      <% end %>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<%=  form_with(model: @user, local: true, data: { turbo: false }) do |f|%>
  <div class="form-group">
    <%= f.label :username %>
    <%= f.text_field :username, class: "form-control", placeholder: "Enter Username" %>
  </div>
  <div class="form-group">
    <%= f.label :email  %>
    <%= f.email_field :email, class: "form-control", placeholder: "Enter Email" %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control", placeholder: "Enter Password" %>
  </div>
  <%= f.submit(@user.new_record? ? 'Sign up' : 'Update Account', class: "btn btn-primary mr-2") %>
  <%= link_to '[ Cancel and return to Articles ]', articles_path %>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <h1>Edit User</h1>
  <%= render 'form' %>
</div>

app/views/users/index.html.erb
<div class="container margin-top">
  <h1>Blog Members</h1>
  <div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
  </div>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Username</th>
        <th>Email</th>
        <th># of Articles</th>
        <th>Joined</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.username, user %></td>
          <td><%= user.email %></td>
          <td><%= user.articles.length %></td>
          <td><small><%= time_ago_in_words(user.created_at) %></small></td>
          <td>
            <%= link_to "View Profile", user, class: "btn btn-primary" %>
            <% if logged_in? && (user == current_user || current_user.admin?) %>
              <%= link_to 'Edit', edit_user_path(user), class: "btn btn-warning" %>
              <%= link_to "Delete", user, data: { turbo_method: :delete, turbo_confirm: "Are you sure, this will delete all articles associated with this account?"}, class: "btn btn-danger" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <h1>Sign Up</h1>
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1><%= @user.username %>'s Profile</h1>
  <% if logged_in? && @user == current_user %>
    <%= link_to "Edit Profile", edit_user_path(@user), class: "btn btn-warning" %>
    <%= link_to "Delete Profile", @user, data: { turbo_method: :delete, turbo_confirm: "Are you sure, this will delete all articles associated with you account?"}, class: "btn btn-danger" %>
  <% end %>
  <h3>Articles</h3>
  <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>
  <%= render 'articles/articles' %>
  <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>
</div>